### ISSUE TITLE
Implement strategy for OAUTH

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/api-gateway#10]
Depending on OAUTH type of auth implement the following scenarios:
7. Expose service and secure with Oatuh2 scopes (client credentials grant supported) - Virtual Service + Access Rule
8. Expose service and secure with Oauth2 scopes on paths - Virtual Service + Access rule

For more details see comments in kyma-project/kyma#5084

**Comment by Demonsthere** [comment]
OUATH strategy is mostly implemented, however as for now we only support securing the whole service. Per path customisation is to be added at a later date
