### ISSUE TITLE
Add validation for jwks_urls field in jwt handler

### ISSUE THREAD

**Issue by kubadz** [kyma-incubator/api-gateway#100]
**Is your feature request related to a problem? Please describe.**

If the URL provided in `jwks_urls` configuration doesn't contain a protocol, Oathkeeper returns a code 500 in a response to a request sent to an exposed application. The response nor the logs from an Oathkeeper pod don't inform what is a cause of the problem, so the user has no idea that the entered URL is wrong.

**Describe the solution you'd like**

Adding validation to the `jwks_urls` field on api-gateway level. Setting the status of APIRule to inform a user, that the provided value is invalid.

**Describe alternatives you've considered**

An alternative solution might be to default the protocol to `https` if not present in the URL. However, that would need an entry in the documentation. Also - I think that it is better to explicitly inform the user that the configuration is invalid with validation, than to implicitly fix it in the application code.

**Comment by veichtj** [comment]
Will be finally handled within : https://github.com/kyma-incubator/api-gateway/issues/136
