### ISSUE TITLE
Implement strategy for JWT

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/api-gateway#11]
Depending on JWT type of auth implement the following scenarios:

1. Expose entire service using virtual service
2. Expose and secure entire service with JWT authentication (Virtual Service + istio policy)
3. Expose service with JWT authentication on selected paths (Virtual Service + oathkeeper access rule)
4. Expose service with JWT authentication including scopes on paths (Virtual Service + AR)
5. Expose and secure entire service with JWT authentication including scopes (Virtual Service + AR)
6. Expose service with JWT authentication but with path whitelisting(excluding) (Virtual Service + istio policy)

For more details see comments in kyma-project/kyma#5084

**Comment by Demonsthere** [comment]
State of the issue:
- JWT_ALL mode has been implemented. 
- JWT_INCLUDE and JWT_EXCLUDE is still ToDo, however has been pushed to a later date

**Comment by strekm** [comment]
Rest of scenarios will be implemented in separate issues
