### ISSUE TITLE
Add validating webhook for API Gateway

### ISSUE THREAD

**Issue by cnvergence** [kyma-incubator/api-gateway#143]
**Is your feature request related to a problem? Please describe.**
We already have a lot of validation checks implemented, but they are executed after creating/updating the API Rule.
So if the user provides a wrongly configured resource, it will set the status to skipped and won't create/update Virtual Service or Access Rule, but the API Rule will still be there.

**Describe the solution you'd like**
I suggest implementing a validating webhook to ensure that a wrongly configured API Rule won't create any resource on the Kubernetes cluster.

**Additional context**
[Implementation guide](https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html)

**Comment by strekm** [comment]
closing in favour of: https://github.com/kyma-project/api-gateway/issues/2
