### ISSUE TITLE
Handle API Status

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/api-gateway#8]
- Extend API-Gateway status with status of Istio VirtualService, Policy, and AccessRule. 
- Add a field for an observed generation 
- Handle update on the status
- Write unit tests
- Document the status in README file

**Comment by pbochynski** [comment]
I am looking for any documentation in the linked PR. Cannot find it :(

**Comment by piotrmsc** [comment]
https://github.com/kyma-incubator/api-gateway/pull/47
